# docker version 3 builder

version: "3.1"

services:
  tor:
    image: lizz0thabet/tor-hidden-service:$CUR_TAG
    build:
      context: .
      args:
        tor_version: $TOR_VERSION
        torsocks_version: $TORSOCKS_VERSION
